from __future__ import annotations

import math
import re
from collections.abc import AsyncIterable, AsyncIterator, Mapping
from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING, Literal, Protocol

if TYPE_CHECKING:
    from mirror_api.synthetic_dataset.prompt_material import EphemeralPrompt

SYNTHETIC_IMAGE_MEDIA_TYPES = frozenset({"image/jpeg", "image/png", "image/webp"})
MAX_SYNTHETIC_GENERATED_IMAGE_BYTES = 20 * 1024 * 1024
MAX_SYNTHETIC_FACE_OBSERVATIONS = 16
MAX_SYNTHETIC_LANDMARKS_PER_FACE = 512
MAX_SYNTHETIC_GEOMETRY_MEASUREMENTS = 128
MAX_SYNTHETIC_GENERATION_PARAMETERS = 32
MAX_SYNTHETIC_SEED = (1 << 63) - 1
_OPAQUE_REFERENCE = re.compile(r"^[a-z][a-z0-9_-]{2,63}$")


def _require_opaque_reference(value: str, *, field_name: str) -> None:
    """Reject URLs, object keys and provider-specific identifiers at the port boundary."""
    if not _OPAQUE_REFERENCE.fullmatch(value):
        raise ValueError(f"{field_name} must use the opaque first-party reference syntax")


def _require_synthetic_subject(subject_kind: str) -> None:
    if subject_kind != "synthetic":
        raise ValueError("provider contract only accepts synthetic subjects")


@dataclass(frozen=True)
class GeneratedImagePayload:
    """Bounded generated bytes; never a URL, object key, SDK value or raw response."""

    content: bytes
    media_type: Literal["image/jpeg", "image/png", "image/webp"]
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        if type(self.content) is not bytes:
            raise ValueError("generated image content must be immutable bytes")
        if not 0 < len(self.content) <= MAX_SYNTHETIC_GENERATED_IMAGE_BYTES:
            raise ValueError("generated image content is outside the allowed size boundary")
        if self.media_type not in SYNTHETIC_IMAGE_MEDIA_TYPES:
            raise ValueError("generated image media type is not allowed")

    @property
    def byte_size(self) -> int:
        return len(self.content)


@dataclass(frozen=True)
class SyntheticOutputSpecification:
    """Requested bounded image shape and MIME, without a provider-specific option bag."""

    media_type: Literal["image/jpeg", "image/png", "image/webp"]
    width: int
    height: int
    max_byte_size: int

    def __post_init__(self) -> None:
        if self.media_type not in SYNTHETIC_IMAGE_MEDIA_TYPES:
            raise ValueError("synthetic output media type is not allowed")
        if self.width < 1 or self.height < 1 or self.width > 8192 or self.height > 8192:
            raise ValueError("synthetic output dimensions are outside the allowed boundary")
        if self.width * self.height > 40_000_000:
            raise ValueError("synthetic output pixel count is outside the allowed boundary")
        if not 0 < self.max_byte_size <= MAX_SYNTHETIC_GENERATED_IMAGE_BYTES:
            raise ValueError("synthetic output maximum bytes are outside the allowed boundary")


GenerationParameterValue = bool | int | float
SyntheticGenerationSourceKind = Literal[
    "CODEX_NATIVE_IMAGEGEN",
    "PROGRAMMATIC_PROVIDER",
    "DETERMINISTIC_FIXTURE",
]


@dataclass(frozen=True)
class GenerationParameter:
    """One explicit scalar parameter; free-form strings/JSON cannot cross this port."""

    parameter_key: str
    value: GenerationParameterValue

    def __post_init__(self) -> None:
        _require_opaque_reference(self.parameter_key, field_name="generation parameter key")
        if type(self.value) not in {bool, int, float}:
            raise ValueError("generation parameter value must be a scalar number or boolean")
        if isinstance(self.value, float) and not math.isfinite(self.value):
            raise ValueError("generation parameter value must be finite")


def _validate_generation_parameters(parameters: tuple[GenerationParameter, ...]) -> None:
    if len(parameters) > MAX_SYNTHETIC_GENERATION_PARAMETERS:
        raise ValueError("generation parameters exceed the allowed cardinality boundary")
    keys = [parameter.parameter_key for parameter in parameters]
    if len(set(keys)) != len(keys):
        raise ValueError("generation parameter keys must be unique")


def _validate_seed(seed: int | None, *, field_name: str) -> None:
    if seed is not None and (type(seed) is not int or seed < 0 or seed > MAX_SYNTHETIC_SEED):
        raise ValueError(f"{field_name} must be a bounded non-negative integer or None")


@dataclass(frozen=True)
class GenerationBudgetContext:
    currency: Literal["CNY", "USD"]
    max_amount_micros: int
    pricing_snapshot_reference: str

    def __post_init__(self) -> None:
        if self.currency not in {"CNY", "USD"}:
            raise ValueError("generation budget currency is not allowed")
        if self.max_amount_micros < 0:
            raise ValueError("generation budget maximum must not be negative")
        _require_opaque_reference(
            self.pricing_snapshot_reference, field_name="pricing snapshot reference"
        )


@dataclass(frozen=True)
class ProviderSafetyFact:
    policy_reference: str
    outcome: Literal["passed", "rejected"]
    reason_code: str

    def __post_init__(self) -> None:
        _require_opaque_reference(self.policy_reference, field_name="safety policy reference")
        _require_opaque_reference(self.reason_code, field_name="safety reason code")
        if self.outcome not in {"passed", "rejected"}:
            raise ValueError("provider safety outcome is not allowed")


@dataclass(frozen=True)
class ProviderCostFact:
    currency: Literal["CNY", "USD"]
    amount_micros: int
    status: Literal["estimated", "final"]

    def __post_init__(self) -> None:
        if self.amount_micros < 0:
            raise ValueError("provider cost amount must not be negative")
        if self.currency not in {"CNY", "USD"}:
            raise ValueError("provider cost currency is not allowed")
        if self.status not in {"estimated", "final"}:
            raise ValueError("provider cost status is not allowed")


@dataclass(frozen=True)
class ProviderProvenanceFact:
    provider_reference: str
    model_reference: str
    model_version_reference: str
    policy_reference: str
    retention_status: Literal["not_retained", "contractually_bounded"]
    output_rights: Literal["internal_evaluation_only", "synthetic_release_permitted"]

    def __post_init__(self) -> None:
        _require_opaque_reference(self.provider_reference, field_name="provider reference")
        _require_opaque_reference(self.model_reference, field_name="model reference")
        _require_opaque_reference(
            self.model_version_reference, field_name="model version reference"
        )
        _require_opaque_reference(self.policy_reference, field_name="provenance policy reference")
        if self.retention_status not in {"not_retained", "contractually_bounded"}:
            raise ValueError("unknown provider retention is forbidden")
        if self.output_rights not in {"internal_evaluation_only", "synthetic_release_permitted"}:
            raise ValueError("provider output rights are not allowed")


@dataclass(frozen=True)
class OfflineSyntheticSourceProvenanceFact:
    """Known facts for an operator-assisted source that is not a runtime Provider."""

    source_kind: Literal["CODEX_NATIVE_IMAGEGEN"]
    provenance_level: Literal["PROVENANCE_ONLY"]
    generation_policy_reference: str
    prompt_template_reference: str
    prompt_digest: str
    generated_at: datetime
    coverage_pack_reference: str | None = None
    coverage_cell_reference: str | None = None
    synthetic_only: Literal[True] = True
    real_person_reference_used: Literal[False] = False
    cost_accounting_mode: Literal["REQUEST_COUNT_ONLY"] = "REQUEST_COUNT_ONLY"
    credit_source: Literal["CODEX_NATIVE_ENTITLEMENT"] = "CODEX_NATIVE_ENTITLEMENT"
    model_reference: None = None
    model_version_reference: None = None
    provider_request_reference: None = None
    provider_actual_seed: None = None
    provider_usage: None = None
    provider_cost: None = None

    def __post_init__(self) -> None:
        if self.source_kind != "CODEX_NATIVE_IMAGEGEN":
            raise ValueError("offline source kind is not allowed")
        if self.provenance_level != "PROVENANCE_ONLY":
            raise ValueError("offline source provenance must remain provenance-only")
        for field_name, reference in (
            ("generation policy reference", self.generation_policy_reference),
            ("prompt template reference", self.prompt_template_reference),
        ):
            _require_opaque_reference(reference, field_name=field_name)
        for optional_field_name, optional_reference in (
            ("coverage pack reference", self.coverage_pack_reference),
            ("coverage cell reference", self.coverage_cell_reference),
        ):
            if optional_reference is not None:
                _require_opaque_reference(optional_reference, field_name=optional_field_name)
        if re.fullmatch(r"[0-9a-f]{64}", self.prompt_digest) is None:
            raise ValueError("offline source prompt digest must be lowercase SHA-256")
        if self.generated_at.tzinfo is None or self.generated_at.utcoffset() is None:
            raise ValueError("offline source generation timestamp must be timezone-aware")
        if self.synthetic_only is not True or self.real_person_reference_used is not False:
            raise ValueError(
                "offline source must be synthetic-only without a real-person reference"
            )
        if self.cost_accounting_mode != "REQUEST_COUNT_ONLY":
            raise ValueError("offline source cost accounting must use request counts")
        if self.credit_source != "CODEX_NATIVE_ENTITLEMENT":
            raise ValueError("offline source credit source is not allowed")
        if any(
            value is not None
            for value in (
                self.model_reference,
                self.model_version_reference,
                self.provider_request_reference,
                self.provider_actual_seed,
                self.provider_usage,
                self.provider_cost,
            )
        ):
            raise ValueError("offline source unknown provenance facts must remain null")


@dataclass(frozen=True)
class SyntheticGenerationRequest:
    """First-party generation intent with no prompt plaintext, URL or user-asset input."""

    request_reference: str
    generation_policy_reference: str
    prompt_template_reference: str
    output_specification: SyntheticOutputSpecification
    generation_parameters: tuple[GenerationParameter, ...]
    seed: int | None
    budget: GenerationBudgetContext
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        _require_opaque_reference(self.request_reference, field_name="generation request reference")
        _require_opaque_reference(
            self.generation_policy_reference, field_name="generation policy reference"
        )
        _require_opaque_reference(
            self.prompt_template_reference, field_name="prompt template reference"
        )
        _validate_generation_parameters(self.generation_parameters)
        _validate_seed(self.seed, field_name="generation seed")


@dataclass(frozen=True)
class SyntheticGenerationResult:
    request_reference: str
    provider_run_reference: str
    payload: GeneratedImagePayload
    safety: ProviderSafetyFact
    cost: ProviderCostFact
    provenance: ProviderProvenanceFact
    provider_actual_seed: int | None
    provider_actual_parameters: tuple[GenerationParameter, ...]
    reproducibility_level: Literal["BIT_EXACT", "SEED_REPLAYABLE", "PROVENANCE_ONLY"]
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        _require_opaque_reference(self.request_reference, field_name="generation request reference")
        _require_opaque_reference(self.provider_run_reference, field_name="provider run reference")
        _validate_seed(self.provider_actual_seed, field_name="provider actual seed")
        _validate_generation_parameters(self.provider_actual_parameters)
        if self.reproducibility_level not in {
            "BIT_EXACT",
            "SEED_REPLAYABLE",
            "PROVENANCE_ONLY",
        }:
            raise ValueError("generation reproducibility level is not allowed")


@dataclass(frozen=True)
class FaceLandmark:
    landmark_code: str
    x: float
    y: float
    confidence: float

    def __post_init__(self) -> None:
        _require_opaque_reference(self.landmark_code, field_name="landmark code")
        if not 0.0 <= self.x <= 1.0 or not 0.0 <= self.y <= 1.0:
            raise ValueError("landmark coordinates must be normalized to the image bounds")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("landmark confidence must be between zero and one")


@dataclass(frozen=True)
class FaceLandmarkSet:
    coordinate_system: Literal["normalized_image_v1"]
    landmarks: tuple[FaceLandmark, ...]

    def __post_init__(self) -> None:
        if self.coordinate_system != "normalized_image_v1":
            raise ValueError("landmark coordinate system is not allowed")
        if not self.landmarks or len(self.landmarks) > MAX_SYNTHETIC_LANDMARKS_PER_FACE:
            raise ValueError("landmark set is outside the allowed cardinality boundary")
        if len({landmark.landmark_code for landmark in self.landmarks}) != len(self.landmarks):
            raise ValueError("landmark codes must be unique within a face")


@dataclass(frozen=True)
class PoseEstimate:
    yaw_degrees: float
    pitch_degrees: float
    roll_degrees: float
    confidence: float

    def __post_init__(self) -> None:
        if any(
            abs(angle) > 180.0
            for angle in (self.yaw_degrees, self.pitch_degrees, self.roll_degrees)
        ):
            raise ValueError("pose angles must be within the closed 180-degree boundary")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("pose confidence must be between zero and one")


@dataclass(frozen=True)
class GeometryMeasurement:
    measurement_code: str
    value: float
    confidence: float
    measurement_version: str

    def __post_init__(self) -> None:
        _require_opaque_reference(self.measurement_code, field_name="geometry measurement code")
        _require_opaque_reference(
            self.measurement_version, field_name="geometry measurement version"
        )
        if not -10_000.0 <= self.value <= 10_000.0:
            raise ValueError("geometry measurement value is outside the bounded range")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("geometry measurement confidence must be between zero and one")


@dataclass(frozen=True)
class FaceObservation:
    observation_reference: str
    landmarks: FaceLandmarkSet
    pose: PoseEstimate
    geometry_measurements: tuple[GeometryMeasurement, ...]

    def __post_init__(self) -> None:
        _require_opaque_reference(
            self.observation_reference, field_name="face observation reference"
        )
        if len(self.geometry_measurements) > MAX_SYNTHETIC_GEOMETRY_MEASUREMENTS:
            raise ValueError("geometry measurements exceed the allowed cardinality boundary")
        codes = [measurement.measurement_code for measurement in self.geometry_measurements]
        if len(set(codes)) != len(codes):
            raise ValueError("geometry measurement codes must be unique within a face")


@dataclass(frozen=True)
class SyntheticVisionRequest:
    request_reference: str
    image: GeneratedImagePayload
    vision_policy_reference: str
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        _require_opaque_reference(self.request_reference, field_name="vision request reference")
        _require_opaque_reference(
            self.vision_policy_reference, field_name="vision policy reference"
        )
        _require_synthetic_subject(self.image.subject_kind)


@dataclass(frozen=True)
class SyntheticVisionResult:
    request_reference: str
    provider_run_reference: str
    observations: tuple[FaceObservation, ...]
    safety: ProviderSafetyFact
    cost: ProviderCostFact
    provenance: ProviderProvenanceFact
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        _require_opaque_reference(self.request_reference, field_name="vision request reference")
        _require_opaque_reference(self.provider_run_reference, field_name="provider run reference")
        if len(self.observations) > MAX_SYNTHETIC_FACE_OBSERVATIONS:
            raise ValueError("face observations exceed the allowed cardinality boundary")
        references = [observation.observation_reference for observation in self.observations]
        if len(set(references)) != len(references):
            raise ValueError("face observation references must be unique")


@dataclass(frozen=True)
class SyntheticStorageWriteRequest:
    """Synthetic-only internal write intent; storage references are opaque, never object keys."""

    storage_reference: str
    payload: GeneratedImagePayload
    provenance: ProviderProvenanceFact | OfflineSyntheticSourceProvenanceFact
    subject_kind: Literal["synthetic"] = "synthetic"

    def __post_init__(self) -> None:
        _require_synthetic_subject(self.subject_kind)
        _require_synthetic_subject(self.payload.subject_kind)
        _require_opaque_reference(self.storage_reference, field_name="synthetic storage reference")


@dataclass(frozen=True)
class SyntheticStoredImage:
    storage_reference: str
    byte_size: int
    media_type: Literal["image/jpeg", "image/png", "image/webp"]
    sha256: str
    namespace: Literal["internal_synthetic_v1"] = "internal_synthetic_v1"

    def __post_init__(self) -> None:
        if not isinstance(self.storage_reference, str):
            raise ValueError("synthetic storage reference must be text")
        _require_opaque_reference(self.storage_reference, field_name="synthetic storage reference")
        if (
            type(self.byte_size) is not int
            or self.byte_size <= 0
            or self.byte_size > MAX_SYNTHETIC_GENERATED_IMAGE_BYTES
        ):
            raise ValueError("stored synthetic image size is outside the allowed boundary")
        if not isinstance(self.media_type, str) or not isinstance(self.sha256, str):
            raise ValueError("stored synthetic image metadata must use scalar text")
        if self.media_type not in SYNTHETIC_IMAGE_MEDIA_TYPES:
            raise ValueError("stored synthetic image media type is not allowed")
        if not re.fullmatch(r"[0-9a-f]{64}", self.sha256):
            raise ValueError("stored synthetic image checksum must be lowercase SHA-256")
        if self.namespace != "internal_synthetic_v1":
            raise ValueError("stored image must use the internal synthetic namespace")


class SyntheticStorageConflictError(Exception):
    """An opaque synthetic reference already contains different immutable bytes."""

    def __init__(self) -> None:
        super().__init__("synthetic storage conflict")


class SyntheticStorageOperationError(Exception):
    """A fail-closed storage rejection that never exposes a path or object key."""

    def __init__(self, reason: str) -> None:
        if not re.fullmatch(r"[a-z][a-z0-9_]{2,63}", reason):
            reason = "synthetic_storage_rejected"
        self.reason = reason
        super().__init__("synthetic storage operation was rejected")


class SanitizedObjectConflictError(Exception):
    """A canonical sanitized key already exists with different content."""

    def __init__(self) -> None:
        super().__init__("sanitized object conflict")


@dataclass(frozen=True)
class PrivateUploadGrant:
    method: Literal["PUT"]
    url: str
    required_headers: Mapping[str, str]
    expires_at: datetime


@dataclass(frozen=True)
class PrivateDownloadGrant:
    method: Literal["GET"]
    url: str
    required_headers: Mapping[str, str]
    expires_at: datetime


@dataclass(frozen=True)
class QuarantineObjectMetadata:
    byte_size: int
    content_type: str
    sha256: str
    etag: str
    uploaded_at: datetime


@dataclass(frozen=True)
class SanitizedObjectMetadata:
    """Server-derived facts about a canonical sanitized object."""

    byte_size: int
    content_type: Literal["image/jpeg"]
    sha256: str


@dataclass(frozen=True)
class DataExportObjectMetadata:
    """Server-derived facts about a private deterministic export archive."""

    byte_size: int
    content_type: Literal["application/zip"]
    sha256: str


DeleteResult = Literal["deleted", "not_found"]


@dataclass(frozen=True)
class AgentPlan:
    intent: str
    operations: tuple[str, ...]
    provider_run_id: str


@dataclass(frozen=True)
class PaymentCommand:
    provider: str
    operation: str
    idempotency_key_hash: str


AgeAssuranceStatus = Literal["verified", "not_verified", "indeterminate"]


@dataclass(frozen=True)
class AgeAssuranceResult:
    """The minimum age-assurance conclusion permitted outside a provider boundary."""

    status: AgeAssuranceStatus
    provider_reference: str
    provider_version: str
    policy_version: str
    expires_at: datetime | None = None

    def __post_init__(self) -> None:
        if self.status not in ("verified", "not_verified", "indeterminate"):
            raise ValueError(
                "age assurance status must be verified, not_verified, or indeterminate"
            )


class SmsProvider(Protocol):
    async def send_verification_code(
        self,
        *,
        destination_phone: str,
        verification_code: str,
        request_reference: str,
    ) -> str:
        """Send an OTP and return the provider message identifier."""


class AgeAssuranceProvider(Protocol):
    async def verify_credential(
        self, *, credential: str, request_reference: str
    ) -> AgeAssuranceResult:
        """Exchange an external credential for a minimum 18+ assurance result."""


class ObjectStorageProvider(Protocol):
    async def create_private_download_grant(
        self, *, object_key: str, request_reference: str
    ) -> PrivateDownloadGrant: ...

    async def create_private_upload_grant(
        self,
        *,
        object_key: str,
        content_type: str,
        content_length: int,
        checksum_sha256: str,
    ) -> PrivateUploadGrant: ...

    async def inspect_quarantine_object(
        self, *, object_key: str
    ) -> QuarantineObjectMetadata | None: ...

    async def delete_quarantine_object(self, *, object_key: str) -> DeleteResult: ...

    def stream_quarantine_object(self, *, object_key: str) -> AsyncIterator[bytes]: ...

    async def create_sanitized_object_if_absent(
        self,
        *,
        object_key: str,
        content_type: Literal["image/jpeg"],
        content_length: int,
        checksum_sha256: str,
        body: AsyncIterable[bytes],
    ) -> SanitizedObjectMetadata: ...

    async def inspect_sanitized_object(
        self, *, object_key: str
    ) -> SanitizedObjectMetadata | None: ...

    def stream_sanitized_object(self, *, object_key: str) -> AsyncIterator[bytes]: ...

    async def delete_sanitized_object(self, *, object_key: str) -> DeleteResult: ...

    async def create_data_export_if_absent(
        self,
        *,
        object_key: str,
        content_length: int,
        checksum_sha256: str,
        body: AsyncIterable[bytes],
    ) -> DataExportObjectMetadata: ...

    async def inspect_data_export(self, *, object_key: str) -> DataExportObjectMetadata | None: ...

    def stream_data_export(self, *, object_key: str) -> AsyncIterator[bytes]: ...

    async def delete_data_export(self, *, object_key: str) -> DeleteResult: ...


class SyntheticObjectStorageProvider(Protocol):
    """Private P2 namespace, intentionally separate from every user-asset storage port."""

    async def store_generated_image_if_absent(
        self, *, request: SyntheticStorageWriteRequest
    ) -> SyntheticStoredImage: ...

    async def inspect_generated_image(
        self, *, storage_reference: str
    ) -> SyntheticStoredImage | None: ...

    def stream_generated_image(self, *, storage_reference: str) -> AsyncIterator[bytes]: ...

    async def delete_generated_image(self, *, storage_reference: str) -> DeleteResult: ...


class VisionProvider(Protocol):
    async def inspect_synthetic(
        self, *, request: SyntheticVisionRequest
    ) -> SyntheticVisionResult: ...


class ImageGenerationProvider(Protocol):
    async def generate_synthetic(
        self, *, request: SyntheticGenerationRequest, prompt: EphemeralPrompt
    ) -> SyntheticGenerationResult: ...


class AgentProvider(Protocol):
    async def create_plan(self, *, intent: str) -> AgentPlan: ...


class PaymentProvider(Protocol):
    async def execute(self, command: PaymentCommand) -> str: ...
