/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sms-challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sms Challenge */
        post: operations["create_sms_challenge_api_v1_auth_sms_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questionnaires/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Questionnaire Run */
        post: operations["create_questionnaire_run_api_v1_questionnaires_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editing-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Editing Session */
        post: operations["create_editing_session_api_v1_editing_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["create_checkout_api_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | unknown[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "ready" | "limited";
            /**
             * Service
             * @default mirror-api
             */
            service: string;
            /** Version */
            version: string;
            /** Dependencies */
            dependencies: {
                [key: string]: "available" | "unavailable" | "not_checked";
            };
        };
        /** PlaceholderRequest */
        PlaceholderRequest: {
            /** Intent */
            intent?: string | null;
        };
        /** Settings */
        Settings: {
            /**
             * App Env
             * @default development
             * @enum {string}
             */
            app_env: "development" | "test" | "ci" | "production";
            /**
             * App Version
             * @default 0.1.0
             */
            app_version: string;
            /**
             * Log Level
             * @default INFO
             */
            log_level: string;
            /**
             * Debug
             * @default false
             */
            debug: boolean;
            /**
             * Database Url
             * @default postgresql+psycopg://mirror:mirror_dev_only@127.0.0.1:5432/mirror
             */
            database_url: string;
            /**
             * Redis Url
             * @default redis://127.0.0.1:6379/0
             */
            redis_url: string;
            /** Cors Origins */
            cors_origins?: string[];
            /**
             * Auth Token Secret
             * @default development-only-not-for-production
             */
            auth_token_secret: string;
            /**
             * Auth Callback Url
             * @default http://127.0.0.1:3000/auth/callback
             */
            auth_callback_url: string;
            /**
             * Sms Provider
             * @default mock
             * @enum {string}
             */
            sms_provider: "mock" | "tencent";
            /**
             * Storage Provider
             * @default local
             * @enum {string}
             */
            storage_provider: "local" | "tencent_cos";
            /**
             * Local Storage Root
             * Format: path
             * @default .local-storage
             */
            local_storage_root: string;
            /**
             * Object Storage Private
             * @default true
             */
            object_storage_private: boolean;
            /**
             * Signed Url Ttl Seconds
             * @default 300
             */
            signed_url_ttl_seconds: number;
            /**
             * Vision Provider
             * @default mock
             * @enum {string}
             */
            vision_provider: "mock" | "disabled" | "verified_external" | "tencent_candidate";
            /**
             * Image Generation Provider
             * @default mock
             * @enum {string}
             */
            image_generation_provider: "mock" | "disabled" | "verified_external" | "tencent_candidate";
            /**
             * Agent Provider
             * @default mock
             * @enum {string}
             */
            agent_provider: "mock" | "disabled" | "verified_external" | "tencent_candidate";
            /**
             * Task Runner
             * @default local
             * @enum {string}
             */
            task_runner: "local" | "celery";
            /**
             * Sensitive Processing Enabled
             * @default false
             */
            sensitive_processing_enabled: boolean;
            /**
             * Legal Review Status
             * @default required
             * @enum {string}
             */
            legal_review_status: "required" | "approved";
            /**
             * Provider Benchmark Status
             * @default required
             * @enum {string}
             */
            provider_benchmark_status: "required" | "approved";
            /** Tencent Secret Id */
            tencent_secret_id?: string | null;
            /** Tencent Secret Key */
            tencent_secret_key?: string | null;
            /** Tencent Region */
            tencent_region?: string | null;
            /** Tencent Cos Bucket */
            tencent_cos_bucket?: string | null;
            /** Tencent Sms App Id */
            tencent_sms_app_id?: string | null;
            /** Tencent Sms Sign Name */
            tencent_sms_sign_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /**
             * Service
             * @default mirror-api
             */
            service: string;
            /** Version */
            version: string;
            /**
             * Api Version
             * @default v1
             */
            api_version: string;
        };
        /** SelfStateContract */
        SelfStateContract: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Baseline Face Model Id */
            baseline_face_model_id: string;
            /** State Schema Version */
            state_schema_version: string;
            /** Reliable Dimensions */
            reliable_dimensions: string[];
            /** Unreliable Dimensions */
            unreliable_dimensions: string[];
        };
        /** DesiredDeltaDimensionContract */
        DesiredDeltaDimensionContract: {
            /** Dimension Key */
            dimension_key: string;
            /**
             * Direction
             * @enum {integer}
             */
            direction: -1 | 0 | 1;
            /** Magnitude */
            magnitude: number;
            /** Preference Confidence */
            preference_confidence: number;
            /** Generalization Confidence */
            generalization_confidence: number;
            /** Transfer Confidence */
            transfer_confidence: number;
            /**
             * User Lock
             * @enum {string}
             */
            user_lock: "none" | "preserve";
        };
        /** DesiredDeltaProfileContract */
        DesiredDeltaProfileContract: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Self State Version Id */
            self_state_version_id: string;
            /** Inference Algorithm Version */
            inference_algorithm_version: string;
            /** Evidence Fusion Version */
            evidence_fusion_version: string;
            /** Dimensions */
            dimensions: components["schemas"]["DesiredDeltaDimensionContract"][];
        };
        /** QuestionnaireRunContextContract */
        QuestionnaireRunContextContract: {
            /** Baseline Face Model Id */
            baseline_face_model_id: string;
            /** Self State Version Id */
            self_state_version_id: string;
            /** Question Bank Version */
            question_bank_version: string;
            /** Routing Algorithm Version */
            routing_algorithm_version: string;
            /** Route Seed */
            route_seed: string;
            /** Measurement Normalization Version */
            measurement_normalization_version: string;
            /** Morphology Descriptor Version */
            morphology_descriptor_version: string;
            /** Neighborhood Metric Version */
            neighborhood_metric_version: string;
            /** Stimulus Generator Version */
            stimulus_generator_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Settings"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    create_sms_challenge_api_v1_auth_sms_challenges_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_questionnaire_run_api_v1_questionnaires_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_profile_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_editing_session_api_v1_editing_sessions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_checkout_api_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceholderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
