"""Phase 0 PostgreSQL foundation.

Revision ID: 0001_phase0
Revises:
Create Date: 2026-08-15
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_phase0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _install_immutable_triggers() -> None:
    op.execute(
        """
        CREATE FUNCTION mirror_reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'immutable record cannot be updated or deleted';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in (
        "baseline_measurements",
        "baseline_morphology_descriptors",
        "question_templates",
        "question_instances",
        "questionnaire_routes",
        "question_responses",
        "desired_delta_profile_versions",
        "desired_delta_dimensions",
        "style_profile_versions",
        "identity_constraint_versions",
        "self_transfer_validation_responses",
        "aesthetic_profile_versions",
        "consent_records",
        "credit_ledger",
        "ai_content_provenance",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION mirror_reject_mutation();"
        )
    op.execute(
        """
        CREATE FUNCTION mirror_protect_versioned_state() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' OR
               (to_jsonb(NEW) - 'superseded_at') IS DISTINCT FROM
               (to_jsonb(OLD) - 'superseded_at') THEN
                RAISE EXCEPTION 'versioned state evidence is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in ("baseline_face_models", "self_states"):
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_versioned_state "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION mirror_protect_versioned_state();"
        )
    op.execute(
        """
        CREATE FUNCTION mirror_protect_original_asset() RETURNS trigger AS $$
        BEGIN
            IF OLD.asset_role = 'original' AND (
                NEW.asset_role IS DISTINCT FROM OLD.asset_role OR
                NEW.storage_key IS DISTINCT FROM OLD.storage_key OR
                NEW.sha256 IS DISTINCT FROM OLD.sha256 OR
                NEW.byte_size IS DISTINCT FROM OLD.byte_size OR
                NEW.width IS DISTINCT FROM OLD.width OR
                NEW.height IS DISTINCT FROM OLD.height OR
                NEW.mime_type IS DISTINCT FROM OLD.mime_type OR
                NEW.is_ai_generated IS DISTINCT FROM OLD.is_ai_generated OR
                NEW.is_ai_modified IS DISTINCT FROM OLD.is_ai_modified
            ) THEN
                RAISE EXCEPTION 'original asset blob metadata is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_assets_protect_original
        BEFORE UPDATE ON assets
        FOR EACH ROW EXECUTE FUNCTION mirror_protect_original_asset();
        """
    )


def _remove_immutable_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_assets_protect_original ON assets")
    op.execute("DROP FUNCTION IF EXISTS mirror_protect_original_asset()")
    for table_name in ("baseline_face_models", "self_states"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_versioned_state ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS mirror_protect_versioned_state()")
    for table_name in (
        "baseline_measurements",
        "baseline_morphology_descriptors",
        "question_templates",
        "question_instances",
        "questionnaire_routes",
        "question_responses",
        "desired_delta_profile_versions",
        "desired_delta_dimensions",
        "style_profile_versions",
        "identity_constraint_versions",
        "self_transfer_validation_responses",
        "aesthetic_profile_versions",
        "consent_records",
        "credit_ledger",
        "ai_content_provenance",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS mirror_reject_mutation()")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_content_provenance",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("operation_type", sa.String(length=64), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_asset_ids", sa.JSON(), nullable=False),
        sa.Column("prompt_version", sa.String(length=48), nullable=False),
        sa.Column("workflow_version", sa.String(length=48), nullable=False),
        sa.Column("policy_version", sa.String(length=48), nullable=False),
        sa.Column("content_marker_status", sa.String(length=32), nullable=False),
        sa.Column("metadata_marker_status", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("normalized_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_content_provenance")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=48), nullable=False),
        sa.Column("target_id", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "invite_codes",
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("max_uses > 0", name=op.f("ck_invite_codes_positive_max_uses")),
        sa.CheckConstraint(
            "use_count >= 0 AND use_count <= max_uses", name=op.f("ck_invite_codes_valid_use_count")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_invite_codes_code_hash")),
    )
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key_hash", name=op.f("uq_jobs_idempotency_key_hash")),
    )
    op.create_table(
        "model_runs",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("capability", sa.String(length=48), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=48), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("input_asset_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_table(
        "payment_events",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name=op.f("uq_payment_events_provider")
        ),
    )
    op.create_table(
        "phone_verification_challenges",
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_verification_challenges")),
    )
    op.create_index(
        op.f("ix_phone_verification_challenges_phone_hash"),
        "phone_verification_challenges",
        ["phone_hash"],
        unique=False,
    )
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_table(
        "question_bank_versions",
        sa.Column("version", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("qa_version", sa.String(length=48), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_question_bank_versions_version")),
    )
    op.create_table(
        "users",
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("age_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone_hash", name=op.f("uq_users_phone_hash")),
    )
    op.create_table(
        "aesthetic_profiles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("learning_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_aesthetic_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aesthetic_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_aesthetic_profiles_user_id")),
    )
    op.create_table(
        "assets",
        sa.Column("owner_user_id", sa.String(length=32), nullable=True),
        sa.Column("asset_role", sa.String(length=24), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("is_ai_modified", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "asset_role IN ('original','derived','synthetic')",
            name=op.f("ck_assets_valid_asset_role"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_assets_positive_byte_size")),
        sa.CheckConstraint("width > 0 AND height > 0", name=op.f("ck_assets_positive_dimensions")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_assets_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index(op.f("ix_assets_owner_user_id"), "assets", ["owner_user_id"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("consent_type", sa.String(length=48), nullable=False),
        sa.Column("purpose", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=48), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("supersedes_id", sa.String(length=32), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "(action = 'grant' AND granted_at IS NOT NULL AND withdrawn_at IS NULL) OR (action = 'withdraw' AND granted_at IS NULL AND withdrawn_at IS NOT NULL AND supersedes_id IS NOT NULL)",
            name=op.f("ck_consent_records_valid_consent_event"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["consent_records.id"],
            name=op.f("fk_consent_records_supersedes_id_consent_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_consent_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
    )
    op.create_index(
        op.f("ix_consent_records_user_id"), "consent_records", ["user_id"], unique=False
    )
    op.create_table(
        "credit_accounts",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_credit_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_accounts")),
        sa.UniqueConstraint("user_id", name=op.f("uq_credit_accounts_user_id")),
    )
    op.create_table(
        "entitlements",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entitlements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlements")),
    )
    op.create_index(op.f("ix_entitlements_user_id"), "entitlements", ["user_id"], unique=False)
    op.create_index(
        "ix_entitlements_user_feature", "entitlements", ["user_id", "feature"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("actor_key", sa.String(length=96), nullable=False),
        sa.Column("scope", sa.String(length=96), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_reference", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "actor_key", "scope", "key_hash", name=op.f("uq_idempotency_records_actor_key")
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_user_id"), "idempotency_records", ["user_id"], unique=False
    )
    op.create_table(
        "job_attempts",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint("attempt > 0", name=op.f("ck_job_attempts_positive_attempt")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_attempts_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint("job_id", "attempt", name=op.f("uq_job_attempts_job_id")),
    )
    op.create_index(op.f("ix_job_attempts_job_id"), "job_attempts", ["job_id"], unique=False)
    op.create_table(
        "preference_events",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("signal", sa.JSON(), nullable=False),
        sa.Column("user_initiated", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "user_initiated IS TRUE", name=op.f("ck_preference_events_requires_user_signal")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preference_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preference_events")),
    )
    op.create_index(
        op.f("ix_preference_events_user_id"), "preference_events", ["user_id"], unique=False
    )
    op.create_table(
        "question_templates",
        sa.Column("bank_version_id", sa.String(length=32), nullable=False),
        sa.Column("slot_id", sa.String(length=48), nullable=False),
        sa.Column("target_dimension", sa.String(length=96), nullable=False),
        sa.Column("question_purpose", sa.String(length=48), nullable=False),
        sa.Column("stimulus_strategy", sa.String(length=64), nullable=False),
        sa.Column("coverage_role", sa.String(length=48), nullable=False),
        sa.Column("expected_evidence_type", sa.String(length=48), nullable=False),
        sa.Column("validation_requirements", sa.JSON(), nullable=False),
        sa.Column("template_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_version_id"],
            ["question_bank_versions.id"],
            name=op.f("fk_question_templates_bank_version_id_question_bank_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_templates")),
        sa.UniqueConstraint(
            "bank_version_id",
            "slot_id",
            "template_version",
            name=op.f("uq_question_templates_bank_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_question_templates_bank_version_id"),
        "question_templates",
        ["bank_version_id"],
        unique=False,
    )
    op.create_table(
        "style_profile_versions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("negative_preferences", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.JSON(), nullable=False),
        sa.Column("evidence_summary", sa.JSON(), nullable=False),
        sa.Column("inference_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_style_profile_versions_positive_style_profile_version")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_style_profile_versions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_style_profile_versions")),
        sa.UniqueConstraint("user_id", "version", name=op.f("uq_style_profile_versions_user_id")),
    )
    op.create_index(
        op.f("ix_style_profile_versions_user_id"),
        "style_profile_versions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_subscriptions_plan_id_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("provider_reference", name=op.f("uq_subscriptions_provider_reference")),
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "synthetic_identities",
        sa.Column("bank_version_id", sa.String(length=32), nullable=False),
        sa.Column("generator_provider", sa.String(length=64), nullable=False),
        sa.Column("generator_model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=48), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("adult_synthetic_attested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_version_id"],
            ["question_bank_versions.id"],
            name=op.f("fk_synthetic_identities_bank_version_id_question_bank_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_synthetic_identities")),
    )
    op.create_index(
        op.f("ix_synthetic_identities_bank_version_id"),
        "synthetic_identities",
        ["bank_version_id"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("uq_user_sessions_refresh_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "asset_access_audits",
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column("actor_user_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_asset_access_audits_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_access_audits_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_access_audits")),
    )
    op.create_index(
        op.f("ix_asset_access_audits_asset_id"), "asset_access_audits", ["asset_id"], unique=False
    )
    op.create_table(
        "asset_variants",
        sa.Column("source_asset_id", sa.String(length=32), nullable=False),
        sa.Column("result_asset_id", sa.String(length=32), nullable=False),
        sa.Column("variant_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "source_asset_id <> result_asset_id",
            name=op.f("ck_asset_variants_distinct_source_result"),
        ),
        sa.ForeignKeyConstraint(
            ["result_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_variants_result_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_variants_source_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_variants")),
        sa.UniqueConstraint("result_asset_id", name=op.f("uq_asset_variants_result_asset_id")),
    )
    op.create_index(
        op.f("ix_asset_variants_source_asset_id"),
        "asset_variants",
        ["source_asset_id"],
        unique=False,
    )
    op.create_table(
        "baseline_face_models",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("source_asset_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("analyzer_provider", sa.String(length=64), nullable=False),
        sa.Column("analyzer_version", sa.String(length=64), nullable=False),
        sa.Column("analysis_schema_version", sa.String(length=48), nullable=False),
        sa.Column("pose", sa.JSON(), nullable=False),
        sa.Column("quality_metrics", sa.JSON(), nullable=False),
        sa.Column("measurement_normalization_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_baseline_face_models_positive_baseline_face_model_version")
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["assets.id"],
            name=op.f("fk_baseline_face_models_source_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_baseline_face_models_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_face_models")),
        sa.UniqueConstraint("user_id", "version", name=op.f("uq_baseline_face_models_user_id")),
    )
    op.create_index(
        op.f("ix_baseline_face_models_user_id"), "baseline_face_models", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseline_face_models_source_asset_id"),
        "baseline_face_models",
        ["source_asset_id"],
        unique=False,
    )
    op.create_table(
        "credit_ledger",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=48), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=False),
        sa.Column("reference_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_credit_ledger_nonzero_amount")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["credit_accounts.id"],
            name=op.f("fk_credit_ledger_account_id_credit_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_ledger")),
        sa.UniqueConstraint(
            "idempotency_key_hash", name=op.f("uq_credit_ledger_idempotency_key_hash")
        ),
        sa.UniqueConstraint(
            "reference_type", "reference_id", "reason", name=op.f("uq_credit_ledger_reference_type")
        ),
    )
    op.create_index(
        op.f("ix_credit_ledger_account_id"), "credit_ledger", ["account_id"], unique=False
    )
    op.create_table(
        "question_assets",
        sa.Column("synthetic_identity_id", sa.String(length=32), nullable=False),
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column("target_feature", sa.String(length=64), nullable=False),
        sa.Column("target_delta", sa.Numeric(precision=8, scale=5), nullable=False),
        sa.Column("measured_delta", sa.Numeric(precision=8, scale=5), nullable=True),
        sa.Column("measurements", sa.JSON(), nullable=False),
        sa.Column("qa_status", sa.String(length=24), nullable=False),
        sa.Column("qa_version", sa.String(length=48), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_question_assets_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_identity_id"],
            ["synthetic_identities.id"],
            name=op.f("fk_question_assets_synthetic_identity_id_synthetic_identities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_assets")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_question_assets_asset_id")),
    )
    op.create_index(
        op.f("ix_question_assets_synthetic_identity_id"),
        "question_assets",
        ["synthetic_identity_id"],
        unique=False,
    )
    op.create_table(
        "baseline_measurements",
        sa.Column("baseline_face_model_id", sa.String(length=32), nullable=False),
        sa.Column("measurement_key", sa.String(length=96), nullable=False),
        sa.Column("normalized_value", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("measurement_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("measurement_method_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "measurement_confidence >= 0 AND measurement_confidence <= 1",
            name=op.f("ck_baseline_measurements_baseline_measurement_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["baseline_face_model_id"],
            ["baseline_face_models.id"],
            name=op.f("fk_baseline_measurements_baseline_face_model_id_baseline_face_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_measurements")),
        sa.UniqueConstraint(
            "baseline_face_model_id",
            "measurement_key",
            name=op.f("uq_baseline_measurements_baseline_face_model_id"),
        ),
    )
    op.create_index(
        op.f("ix_baseline_measurements_baseline_face_model_id"),
        "baseline_measurements",
        ["baseline_face_model_id"],
        unique=False,
    )
    op.create_table(
        "self_states",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("baseline_face_model_id", sa.String(length=32), nullable=False),
        sa.Column("reliable_dimensions", sa.JSON(), nullable=False),
        sa.Column("unreliable_dimensions", sa.JSON(), nullable=False),
        sa.Column("identity_anchor_reference", sa.JSON(), nullable=False),
        sa.Column("state_schema_version", sa.String(length=48), nullable=False),
        sa.Column("derivation_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_self_states_positive_self_state_version")),
        sa.ForeignKeyConstraint(
            ["baseline_face_model_id"],
            ["baseline_face_models.id"],
            name=op.f("fk_self_states_baseline_face_model_id_baseline_face_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_self_states_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_self_states")),
        sa.UniqueConstraint("user_id", "version", name=op.f("uq_self_states_user_id")),
    )
    op.create_index(
        op.f("ix_self_states_baseline_face_model_id"),
        "self_states",
        ["baseline_face_model_id"],
        unique=False,
    )
    op.create_index(op.f("ix_self_states_user_id"), "self_states", ["user_id"], unique=False)
    op.create_table(
        "baseline_morphology_descriptors",
        sa.Column("source_self_state_id", sa.String(length=32), nullable=False),
        sa.Column("descriptor_version", sa.String(length=48), nullable=False),
        sa.Column("measurement_normalization_version", sa.String(length=48), nullable=False),
        sa.Column("continuous_dimensions", sa.JSON(), nullable=False),
        sa.Column("reliability", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_self_state_id"],
            ["self_states.id"],
            name=op.f("fk_baseline_morphology_descriptors_source_self_state_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_morphology_descriptors")),
        sa.UniqueConstraint(
            "source_self_state_id",
            name=op.f("uq_baseline_morphology_descriptors_source_self_state_id"),
        ),
    )
    op.create_table(
        "identity_constraint_versions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("preserve_regions", sa.JSON(), nullable=False),
        sa.Column("feature_locks", sa.JSON(), nullable=False),
        sa.Column("allowed_delta_bounds", sa.JSON(), nullable=False),
        sa.Column("edit_strength_limits", sa.JSON(), nullable=False),
        sa.Column("context_restrictions", sa.JSON(), nullable=False),
        sa.Column("identity_preservation_requirements", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "version > 0",
            name=op.f("ck_identity_constraint_versions_identity_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_identity_constraint_versions_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_identity_constraint_versions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_constraint_versions")),
        sa.UniqueConstraint(
            "user_id", "version", name=op.f("uq_identity_constraint_versions_user_id")
        ),
    )
    op.create_index(
        op.f("ix_identity_constraint_versions_user_id"),
        "identity_constraint_versions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_constraint_versions_self_state_version_id"),
        "identity_constraint_versions",
        ["self_state_version_id"],
        unique=False,
    )
    op.create_table(
        "questionnaire_runs",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("bank_version_id", sa.String(length=32), nullable=False),
        sa.Column("baseline_face_model_id", sa.String(length=32), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("routing_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("route_seed", sa.String(length=128), nullable=False),
        sa.Column("measurement_normalization_version", sa.String(length=48), nullable=False),
        sa.Column("morphology_descriptor_version", sa.String(length=48), nullable=False),
        sa.Column("neighborhood_metric_version", sa.String(length=48), nullable=False),
        sa.Column("stimulus_generator_version", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("posterior", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "question_count >= 0", name=op.f("ck_questionnaire_runs_nonnegative_question_count")
        ),
        sa.ForeignKeyConstraint(
            ["bank_version_id"],
            ["question_bank_versions.id"],
            name=op.f("fk_questionnaire_runs_bank_version_id_question_bank_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_face_model_id"],
            ["baseline_face_models.id"],
            name=op.f("fk_questionnaire_runs_baseline_face_model_id_baseline_face_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_questionnaire_runs_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_questionnaire_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_runs")),
    )
    op.create_index(
        op.f("ix_questionnaire_runs_baseline_face_model_id"),
        "questionnaire_runs",
        ["baseline_face_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_runs_self_state_version_id"),
        "questionnaire_runs",
        ["self_state_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_runs_bank_version_id"),
        "questionnaire_runs",
        ["bank_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_runs_user_id"), "questionnaire_runs", ["user_id"], unique=False
    )
    op.create_table(
        "desired_delta_profile_versions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("inference_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("evidence_fusion_version", sa.String(length=48), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("evidence_summary", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("questionnaire_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "version > 0",
            name=op.f("ck_desired_delta_profile_versions_delta_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_run_id"],
            ["questionnaire_runs.id"],
            name=op.f("fk_desired_delta_profile_versions_questionnaire_run_id_questionnaire_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_desired_delta_profile_versions_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_desired_delta_profile_versions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_desired_delta_profile_versions")),
        sa.UniqueConstraint(
            "user_id", "version", name=op.f("uq_desired_delta_profile_versions_user_id")
        ),
    )
    op.create_index(
        op.f("ix_desired_delta_profile_versions_self_state_version_id"),
        "desired_delta_profile_versions",
        ["self_state_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_desired_delta_profile_versions_user_id"),
        "desired_delta_profile_versions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "question_instances",
        sa.Column("questionnaire_run_id", sa.String(length=32), nullable=False),
        sa.Column("template_id", sa.String(length=32), nullable=False),
        sa.Column("baseline_face_model_id", sa.String(length=32), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("synthetic_identity_id", sa.String(length=32), nullable=False),
        sa.Column("asset_a_id", sa.String(length=32), nullable=False),
        sa.Column("asset_b_id", sa.String(length=32), nullable=False),
        sa.Column("target_dimension", sa.String(length=96), nullable=False),
        sa.Column("variant_a_delta", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("variant_b_delta", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("neighborhood_distance", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("neighborhood_metric_version", sa.String(length=48), nullable=False),
        sa.Column("excluded_target_dimensions", sa.JSON(), nullable=False),
        sa.Column("randomization_metadata", sa.JSON(), nullable=False),
        sa.Column("question_bank_version", sa.String(length=48), nullable=False),
        sa.Column("routing_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("stimulus_generator_version", sa.String(length=48), nullable=False),
        sa.Column("target_delta", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("non_target_max_error", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("isolation_threshold", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "asset_a_id <> asset_b_id",
            name=op.f("ck_question_instances_distinct_question_instance_assets"),
        ),
        sa.CheckConstraint(
            "isolation_threshold >= 0",
            name=op.f("ck_question_instances_nonnegative_isolation_threshold"),
        ),
        sa.CheckConstraint(
            "neighborhood_distance >= 0",
            name=op.f("ck_question_instances_nonnegative_neighborhood_distance"),
        ),
        sa.CheckConstraint(
            "non_target_max_error >= 0",
            name=op.f("ck_question_instances_nonnegative_non_target_error"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_a_id"],
            ["question_assets.id"],
            name=op.f("fk_question_instances_asset_a_id_question_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["asset_b_id"],
            ["question_assets.id"],
            name=op.f("fk_question_instances_asset_b_id_question_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_face_model_id"],
            ["baseline_face_models.id"],
            name=op.f("fk_question_instances_baseline_face_model_id_baseline_face_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_run_id"],
            ["questionnaire_runs.id"],
            name=op.f("fk_question_instances_questionnaire_run_id_questionnaire_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_question_instances_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_identity_id"],
            ["synthetic_identities.id"],
            name=op.f("fk_question_instances_synthetic_identity_id_synthetic_identities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["question_templates.id"],
            name=op.f("fk_question_instances_template_id_question_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_instances")),
    )
    op.create_index(
        op.f("ix_question_instances_template_id"),
        "question_instances",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_instances_questionnaire_run_id"),
        "question_instances",
        ["questionnaire_run_id"],
        unique=False,
    )
    op.create_table(
        "questionnaire_routes",
        sa.Column("questionnaire_run_id", sa.String(length=32), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("routing_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("route_seed", sa.String(length=128), nullable=False),
        sa.Column("selected_template_ids", sa.JSON(), nullable=False),
        sa.Column("coverage_state", sa.JSON(), nullable=False),
        sa.Column("uncertainty_state", sa.JSON(), nullable=False),
        sa.Column("routing_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["questionnaire_run_id"],
            ["questionnaire_runs.id"],
            name=op.f("fk_questionnaire_routes_questionnaire_run_id_questionnaire_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_questionnaire_routes_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_routes")),
        sa.UniqueConstraint(
            "questionnaire_run_id", name=op.f("uq_questionnaire_routes_questionnaire_run_id")
        ),
    )
    op.create_index(
        op.f("ix_questionnaire_routes_self_state_version_id"),
        "questionnaire_routes",
        ["self_state_version_id"],
        unique=False,
    )
    op.create_table(
        "desired_delta_dimensions",
        sa.Column("desired_delta_profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("dimension_key", sa.String(length=96), nullable=False),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("preference_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("generalization_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("transfer_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("lower_bound", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("upper_bound", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("user_lock", sa.String(length=24), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "user_lock IN ('none','preserve')",
            name=op.f("ck_desired_delta_dimensions_valid_user_lock"),
        ),
        sa.CheckConstraint(
            "direction >= -1 AND direction <= 1",
            name=op.f("ck_desired_delta_dimensions_desired_delta_direction"),
        ),
        sa.CheckConstraint(
            "generalization_confidence >= 0 AND generalization_confidence <= 1",
            name=op.f("ck_desired_delta_dimensions_generalization_confidence_range"),
        ),
        sa.CheckConstraint(
            "lower_bound IS NULL OR upper_bound IS NULL OR lower_bound <= upper_bound",
            name=op.f("ck_desired_delta_dimensions_ordered_desired_delta_bounds"),
        ),
        sa.CheckConstraint(
            "magnitude >= 0",
            name=op.f("ck_desired_delta_dimensions_nonnegative_desired_delta_magnitude"),
        ),
        sa.CheckConstraint(
            "preference_confidence >= 0 AND preference_confidence <= 1",
            name=op.f("ck_desired_delta_dimensions_preference_confidence_range"),
        ),
        sa.CheckConstraint(
            "transfer_confidence >= 0 AND transfer_confidence <= 1",
            name=op.f("ck_desired_delta_dimensions_transfer_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["desired_delta_profile_version_id"],
            ["desired_delta_profile_versions.id"],
            name=op.f(
                "fk_desired_delta_dimensions_desired_delta_profile_version_id_desired_delta_profile_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_desired_delta_dimensions")),
        sa.UniqueConstraint(
            "desired_delta_profile_version_id",
            "dimension_key",
            name=op.f("uq_desired_delta_dimensions_desired_delta_profile_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_desired_delta_dimensions_desired_delta_profile_version_id"),
        "desired_delta_dimensions",
        ["desired_delta_profile_version_id"],
        unique=False,
    )
    op.create_table(
        "question_responses",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("question_instance_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal_choice", sa.Integer(), nullable=False),
        sa.Column("observation_weight", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "ordinal_choice >= -2 AND ordinal_choice <= 2",
            name=op.f("ck_question_responses_ordinal_choice_range"),
        ),
        sa.ForeignKeyConstraint(
            ["question_instance_id"],
            ["question_instances.id"],
            name=op.f("fk_question_responses_question_instance_id_question_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["questionnaire_runs.id"],
            name=op.f("fk_question_responses_run_id_questionnaire_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_responses")),
        sa.UniqueConstraint(
            "run_id", "question_instance_id", name=op.f("uq_question_responses_run_id")
        ),
    )
    op.create_index(
        op.f("ix_question_responses_run_id"), "question_responses", ["run_id"], unique=False
    )
    op.create_table(
        "self_transfer_validation_runs",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("desired_delta_profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("baseline_face_model_id", sa.String(length=32), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("candidate_generation_version", sa.String(length=48), nullable=False),
        sa.Column("refinement_algorithm_version", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_face_model_id"],
            ["baseline_face_models.id"],
            name=op.f(
                "fk_self_transfer_validation_runs_baseline_face_model_id_baseline_face_models"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["desired_delta_profile_version_id"],
            ["desired_delta_profile_versions.id"],
            name=op.f(
                "fk_self_transfer_validation_runs_desired_delta_profile_version_id_desired_delta_profile_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_self_transfer_validation_runs_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_self_transfer_validation_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_self_transfer_validation_runs")),
    )
    op.create_index(
        op.f("ix_self_transfer_validation_runs_user_id"),
        "self_transfer_validation_runs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_self_transfer_validation_runs_desired_delta_profile_version_id"),
        "self_transfer_validation_runs",
        ["desired_delta_profile_version_id"],
        unique=False,
    )
    op.create_table(
        "aesthetic_profile_versions",
        sa.Column("profile_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("self_state_version_id", sa.String(length=32), nullable=False),
        sa.Column("desired_delta_profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("style_profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("identity_constraint_version_id", sa.String(length=32), nullable=False),
        sa.Column("negative_preferences", sa.JSON(), nullable=False),
        sa.Column("context_overrides", sa.JSON(), nullable=False),
        sa.Column("profile_confidence", sa.JSON(), nullable=False),
        sa.Column("evidence_summary", sa.JSON(), nullable=False),
        sa.Column("learning_settings", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("questionnaire_run_id", sa.String(length=32), nullable=True),
        sa.Column("self_transfer_validation_run_id", sa.String(length=32), nullable=True),
        sa.Column("preference_event_id", sa.String(length=32), nullable=True),
        sa.Column("profile_generation_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_aesthetic_profile_versions_positive_profile_version")
        ),
        sa.ForeignKeyConstraint(
            ["desired_delta_profile_version_id"],
            ["desired_delta_profile_versions.id"],
            name=op.f(
                "fk_aesthetic_profile_versions_desired_delta_profile_version_id_desired_delta_profile_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["identity_constraint_version_id"],
            ["identity_constraint_versions.id"],
            name=op.f(
                "fk_aesthetic_profile_versions_identity_constraint_version_id_identity_constraint_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preference_event_id"],
            ["preference_events.id"],
            name=op.f("fk_aesthetic_profile_versions_preference_event_id_preference_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["aesthetic_profiles.id"],
            name=op.f("fk_aesthetic_profile_versions_profile_id_aesthetic_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_run_id"],
            ["questionnaire_runs.id"],
            name=op.f("fk_aesthetic_profile_versions_questionnaire_run_id_questionnaire_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["self_state_version_id"],
            ["self_states.id"],
            name=op.f("fk_aesthetic_profile_versions_self_state_version_id_self_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["self_transfer_validation_run_id"],
            ["self_transfer_validation_runs.id"],
            name=op.f(
                "fk_aesthetic_profile_versions_self_transfer_validation_run_id_self_transfer_validation_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["style_profile_version_id"],
            ["style_profile_versions.id"],
            name=op.f(
                "fk_aesthetic_profile_versions_style_profile_version_id_style_profile_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aesthetic_profile_versions")),
        sa.UniqueConstraint(
            "profile_id", "version", name=op.f("uq_aesthetic_profile_versions_profile_id")
        ),
    )
    op.create_index(
        op.f("ix_aesthetic_profile_versions_identity_constraint_version_id"),
        "aesthetic_profile_versions",
        ["identity_constraint_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aesthetic_profile_versions_style_profile_version_id"),
        "aesthetic_profile_versions",
        ["style_profile_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aesthetic_profile_versions_desired_delta_profile_version_id"),
        "aesthetic_profile_versions",
        ["desired_delta_profile_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aesthetic_profile_versions_self_state_version_id"),
        "aesthetic_profile_versions",
        ["self_state_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aesthetic_profile_versions_profile_id"),
        "aesthetic_profile_versions",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "self_transfer_validation_responses",
        sa.Column("validation_run_id", sa.String(length=32), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("candidate_references", sa.JSON(), nullable=False),
        sa.Column("selected_candidate_reference", sa.String(length=128), nullable=True),
        sa.Column("rejected_candidate_references", sa.JSON(), nullable=False),
        sa.Column("explicit_correction", sa.JSON(), nullable=False),
        sa.Column("transfer_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "round_number > 0",
            name=op.f("ck_self_transfer_validation_responses_round_positive"),
        ),
        sa.CheckConstraint(
            "transfer_confidence >= 0 AND transfer_confidence <= 1",
            name=op.f("ck_self_transfer_validation_responses_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["self_transfer_validation_runs.id"],
            name=op.f(
                "fk_self_transfer_validation_responses_validation_run_id_self_transfer_validation_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_self_transfer_validation_responses")),
        sa.UniqueConstraint(
            "validation_run_id",
            "round_number",
            name=op.f("uq_self_transfer_validation_responses_validation_run_id"),
        ),
    )
    op.create_index(
        op.f("ix_self_transfer_validation_responses_validation_run_id"),
        "self_transfer_validation_responses",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "editing_sessions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("source_asset_id", sa.String(length=32), nullable=False),
        sa.Column("profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("session_preferences", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_version_id"],
            ["aesthetic_profile_versions.id"],
            name=op.f("fk_editing_sessions_profile_version_id_aesthetic_profile_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["assets.id"],
            name=op.f("fk_editing_sessions_source_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_editing_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_editing_sessions")),
    )
    op.create_index(
        op.f("ix_editing_sessions_user_id"), "editing_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "reference_sets",
        sa.Column("profile_version_id", sa.String(length=32), nullable=False),
        sa.Column("front_asset_id", sa.String(length=32), nullable=False),
        sa.Column("three_quarter_asset_id", sa.String(length=32), nullable=False),
        sa.Column("side_asset_id", sa.String(length=32), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["front_asset_id"],
            ["assets.id"],
            name=op.f("fk_reference_sets_front_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_version_id"],
            ["aesthetic_profile_versions.id"],
            name=op.f("fk_reference_sets_profile_version_id_aesthetic_profile_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["side_asset_id"],
            ["assets.id"],
            name=op.f("fk_reference_sets_side_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["three_quarter_asset_id"],
            ["assets.id"],
            name=op.f("fk_reference_sets_three_quarter_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_sets")),
        sa.UniqueConstraint(
            "profile_version_id", name=op.f("uq_reference_sets_profile_version_id")
        ),
    )
    op.create_table(
        "image_versions",
        sa.Column("editing_session_id", sa.String(length=32), nullable=False),
        sa.Column("parent_version_id", sa.String(length=32), nullable=True),
        sa.Column("result_asset_id", sa.String(length=32), nullable=False),
        sa.Column("provenance_id", sa.String(length=32), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "(sequence = 0 AND parent_version_id IS NULL) OR (sequence > 0 AND parent_version_id IS NOT NULL)",
            name=op.f("ck_image_versions_valid_version_lineage"),
        ),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_image_versions_nonnegative_sequence")),
        sa.ForeignKeyConstraint(
            ["editing_session_id"],
            ["editing_sessions.id"],
            name=op.f("fk_image_versions_editing_session_id_editing_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["image_versions.id"],
            name=op.f("fk_image_versions_parent_version_id_image_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["ai_content_provenance.id"],
            name=op.f("fk_image_versions_provenance_id_ai_content_provenance"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_asset_id"],
            ["assets.id"],
            name=op.f("fk_image_versions_result_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_versions")),
        sa.UniqueConstraint(
            "editing_session_id", "sequence", name=op.f("uq_image_versions_editing_session_id")
        ),
        sa.UniqueConstraint("result_asset_id", name=op.f("uq_image_versions_result_asset_id")),
    )
    op.create_index(
        op.f("ix_image_versions_editing_session_id"),
        "image_versions",
        ["editing_session_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("editing_session_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["editing_session_id"],
            ["editing_sessions.id"],
            name=op.f("fk_messages_editing_session_id_editing_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_editing_session_id"), "messages", ["editing_session_id"], unique=False
    )
    op.create_table(
        "edit_operations",
        sa.Column("image_version_id", sa.String(length=32), nullable=False),
        sa.Column("operation_index", sa.Integer(), nullable=False),
        sa.Column("engine", sa.String(length=24), nullable=False),
        sa.Column("operation_type", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("preserve", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "operation_index >= 0", name=op.f("ck_edit_operations_nonnegative_operation_index")
        ),
        sa.ForeignKeyConstraint(
            ["image_version_id"],
            ["image_versions.id"],
            name=op.f("fk_edit_operations_image_version_id_image_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edit_operations")),
        sa.UniqueConstraint(
            "image_version_id", "operation_index", name=op.f("uq_edit_operations_image_version_id")
        ),
    )
    op.create_index(
        op.f("ix_edit_operations_image_version_id"),
        "edit_operations",
        ["image_version_id"],
        unique=False,
    )
    _install_immutable_triggers()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edit_operations_image_version_id"), table_name="edit_operations")
    op.drop_table("edit_operations")
    op.drop_index(op.f("ix_messages_editing_session_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_image_versions_editing_session_id"), table_name="image_versions")
    op.drop_table("image_versions")
    op.drop_table("reference_sets")
    op.drop_index(op.f("ix_editing_sessions_user_id"), table_name="editing_sessions")
    op.drop_table("editing_sessions")
    op.drop_index(
        op.f("ix_self_transfer_validation_responses_validation_run_id"),
        table_name="self_transfer_validation_responses",
    )
    op.drop_table("self_transfer_validation_responses")
    op.drop_index(
        op.f("ix_aesthetic_profile_versions_identity_constraint_version_id"),
        table_name="aesthetic_profile_versions",
    )
    op.drop_index(
        op.f("ix_aesthetic_profile_versions_style_profile_version_id"),
        table_name="aesthetic_profile_versions",
    )
    op.drop_index(
        op.f("ix_aesthetic_profile_versions_desired_delta_profile_version_id"),
        table_name="aesthetic_profile_versions",
    )
    op.drop_index(
        op.f("ix_aesthetic_profile_versions_self_state_version_id"),
        table_name="aesthetic_profile_versions",
    )
    op.drop_index(
        op.f("ix_aesthetic_profile_versions_profile_id"), table_name="aesthetic_profile_versions"
    )
    op.drop_table("aesthetic_profile_versions")
    op.drop_index(
        op.f("ix_self_transfer_validation_runs_user_id"), table_name="self_transfer_validation_runs"
    )
    op.drop_index(
        op.f("ix_self_transfer_validation_runs_desired_delta_profile_version_id"),
        table_name="self_transfer_validation_runs",
    )
    op.drop_table("self_transfer_validation_runs")
    op.drop_index(op.f("ix_question_responses_run_id"), table_name="question_responses")
    op.drop_table("question_responses")
    op.drop_index(
        op.f("ix_desired_delta_dimensions_desired_delta_profile_version_id"),
        table_name="desired_delta_dimensions",
    )
    op.drop_table("desired_delta_dimensions")
    op.drop_index(
        op.f("ix_questionnaire_routes_self_state_version_id"), table_name="questionnaire_routes"
    )
    op.drop_table("questionnaire_routes")
    op.drop_index(op.f("ix_question_instances_template_id"), table_name="question_instances")
    op.drop_index(
        op.f("ix_question_instances_questionnaire_run_id"), table_name="question_instances"
    )
    op.drop_table("question_instances")
    op.drop_index(
        op.f("ix_desired_delta_profile_versions_self_state_version_id"),
        table_name="desired_delta_profile_versions",
    )
    op.drop_index(
        op.f("ix_desired_delta_profile_versions_user_id"),
        table_name="desired_delta_profile_versions",
    )
    op.drop_table("desired_delta_profile_versions")
    op.drop_index(
        op.f("ix_questionnaire_runs_baseline_face_model_id"), table_name="questionnaire_runs"
    )
    op.drop_index(
        op.f("ix_questionnaire_runs_self_state_version_id"), table_name="questionnaire_runs"
    )
    op.drop_index(op.f("ix_questionnaire_runs_bank_version_id"), table_name="questionnaire_runs")
    op.drop_index(op.f("ix_questionnaire_runs_user_id"), table_name="questionnaire_runs")
    op.drop_table("questionnaire_runs")
    op.drop_index(
        op.f("ix_identity_constraint_versions_user_id"), table_name="identity_constraint_versions"
    )
    op.drop_index(
        op.f("ix_identity_constraint_versions_self_state_version_id"),
        table_name="identity_constraint_versions",
    )
    op.drop_table("identity_constraint_versions")
    op.drop_table("baseline_morphology_descriptors")
    op.drop_index(op.f("ix_self_states_baseline_face_model_id"), table_name="self_states")
    op.drop_index(op.f("ix_self_states_user_id"), table_name="self_states")
    op.drop_table("self_states")
    op.drop_index(
        op.f("ix_baseline_measurements_baseline_face_model_id"), table_name="baseline_measurements"
    )
    op.drop_table("baseline_measurements")
    op.drop_index(op.f("ix_question_assets_synthetic_identity_id"), table_name="question_assets")
    op.drop_table("question_assets")
    op.drop_index(op.f("ix_credit_ledger_account_id"), table_name="credit_ledger")
    op.drop_table("credit_ledger")
    op.drop_index(op.f("ix_baseline_face_models_user_id"), table_name="baseline_face_models")
    op.drop_index(
        op.f("ix_baseline_face_models_source_asset_id"), table_name="baseline_face_models"
    )
    op.drop_table("baseline_face_models")
    op.drop_index(op.f("ix_asset_variants_source_asset_id"), table_name="asset_variants")
    op.drop_table("asset_variants")
    op.drop_index(op.f("ix_asset_access_audits_asset_id"), table_name="asset_access_audits")
    op.drop_table("asset_access_audits")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(
        op.f("ix_synthetic_identities_bank_version_id"), table_name="synthetic_identities"
    )
    op.drop_table("synthetic_identities")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_style_profile_versions_user_id"), table_name="style_profile_versions")
    op.drop_table("style_profile_versions")
    op.drop_index(op.f("ix_question_templates_bank_version_id"), table_name="question_templates")
    op.drop_table("question_templates")
    op.drop_index(op.f("ix_preference_events_user_id"), table_name="preference_events")
    op.drop_table("preference_events")
    op.drop_index(op.f("ix_job_attempts_job_id"), table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_index(op.f("ix_idempotency_records_user_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_entitlements_user_id"), table_name="entitlements")
    op.drop_index("ix_entitlements_user_feature", table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_table("credit_accounts")
    op.drop_index(op.f("ix_consent_records_user_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_assets_owner_user_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("aesthetic_profiles")
    op.drop_table("users")
    op.drop_table("question_bank_versions")
    op.drop_table("plans")
    op.drop_index(
        op.f("ix_phone_verification_challenges_phone_hash"),
        table_name="phone_verification_challenges",
    )
    op.drop_table("phone_verification_challenges")
    op.drop_table("payment_events")
    op.drop_table("model_runs")
    op.drop_table("jobs")
    op.drop_table("invite_codes")
    op.drop_table("audit_logs")
    op.drop_table("ai_content_provenance")
    op.execute("DROP FUNCTION IF EXISTS mirror_protect_original_asset()")
    op.execute("DROP FUNCTION IF EXISTS mirror_protect_versioned_state()")
    op.execute("DROP FUNCTION IF EXISTS mirror_reject_mutation()")
    # ### end Alembic commands ###
